import React from 'react';
import { Gavel, Building2, AlertOctagon, ChevronRight } from 'lucide-react';
import { motion, AnimatePresence } from 'motion/react';
import { useScan } from '../context/ScanContext';
import { useSecurity } from '../context/SecurityContext';

export default function LegalDashboard() {
  const { result, actionResult, loading } = useScan();
  const { maskData } = useSecurity();

  const getRiskColor = (level: string) => {
    switch(level) {
      case 'Critical':
      case 'Viral':
        return 'text-red-500 border-red-500 bg-red-500/10';
      case 'High': return 'text-orange-500 border-orange-500 bg-orange-500/10';
      case 'Medium': return 'text-amber-500 border-amber-500 bg-amber-500/10';
      case 'Low': return 'text-emerald-500 border-emerald-500 bg-emerald-500/10';
      default: return 'text-slate-400 border-slate-700 bg-slate-800';
    }
  };

  return (
    <div className="max-w-[1200px] mx-auto space-y-6">
      <div className="mb-8">
        <h1 className="text-2xl font-bold text-white flex items-center gap-2">
          <Gavel className="w-6 h-6 text-indigo-400" /> Legal Affairs & Action Center
        </h1>
        <p className="text-sm text-slate-400 font-mono mt-2">Manage evidence, ownership verification, and takedown protocols.</p>
      </div>

      <AnimatePresence mode="wait">
        {!result && !loading && (
          <motion.div 
            initial={{ opacity: 0 }} animate={{ opacity: 1 }}
            className="p-12 border border-dashed border-white/5 rounded-2xl flex flex-col items-center justify-center text-center bg-[#111827]/50"
          >
            <Gavel className="w-16 h-16 text-slate-600 mb-4" />
            <h2 className="text-lg font-bold text-slate-300">No Target Brief Available</h2>
            <p className="text-sm text-slate-500 font-mono max-w-sm mt-2">Legal analysis is suspended until a valid threat fingerprint is generated by the cybersecurity branch.</p>
          </motion.div>
        )}

        {loading && (
           <motion.div 
             initial={{ opacity: 0 }} animate={{ opacity: 1 }}
             className="p-12 border border-white/5 rounded-2xl flex flex-col items-center justify-center text-center bg-[#111827]/50"
           >
             <div className="animate-pulse flex flex-col items-center">
               <AlertOctagon className="w-12 h-12 text-indigo-500/50 mb-4" />
               <p className="text-xs font-mono text-indigo-400/70 tracking-widest uppercase">Compiling Evidence Database...</p>
             </div>
           </motion.div>
        )}

        {result && (
          <motion.div 
            variants={{
              show: { transition: { staggerChildren: 0.1 } }
            }}
            initial="hidden" animate="show"
            className="space-y-6"
          >
            {/* 1. THREAT SUMMARY (TOP) */}
            <motion.div 
              variants={{ hidden: { opacity: 0, y: 20 }, show: { opacity: 1, y: 0 } }}
              className="grid grid-cols-1 md:grid-cols-3 gap-6"
            >
              <div className="p-6 bg-[#111827] border border-white/5 rounded-2xl flex flex-col items-center text-center shadow-lg">
                <p className="text-[10px] font-mono text-slate-500 uppercase tracking-widest mb-1">Ownership Certainty</p>
                <p className="text-3xl font-black text-white">{result.ownership_analysis.confidence}%</p>
                <div className="w-full bg-slate-800 rounded-full h-1 mt-4 overflow-hidden">
                  <motion.div 
                    initial={{ width: 0 }} animate={{ width: `${result.ownership_analysis.confidence}%` }}
                    className="h-full bg-purple-500 shadow-[0_0_8px_#a855f7]" 
                  />
                </div>
              </div>

              <div className={`p-6 bg-[#111827] border rounded-2xl flex flex-col items-center text-center shadow-lg transition-all ${
                result.risk_level === 'Critical' || result.risk_level === 'High' 
                ? 'border-red-500/20 shadow-red-500/5' 
                : 'border-white/5'
              }`}>
                <p className="text-[10px] font-mono text-slate-500 uppercase tracking-widest mb-1">Violation Severity</p>
                <p className={`text-2xl font-black uppercase ${
                  result.risk_level === 'Critical' || result.risk_level === 'High' ? 'text-red-500' : 'text-emerald-500'
                }`}>
                  {result.risk_level}
                </p>
                <p className="text-[10px] text-slate-500 mt-2 font-mono">Tier-1 Legal Categorization</p>
              </div>

              <div className="p-6 bg-[#111827] border border-white/5 rounded-2xl flex flex-col items-center text-center shadow-lg">
                <p className="text-[10px] font-mono text-slate-500 uppercase tracking-widest mb-1">Detected Samples</p>
                <p className="text-3xl font-black text-indigo-400">{result.flagged_links.length}</p>
                <p className="text-[10px] text-slate-500 mt-2 font-mono">Flagged for immediate action</p>
              </div>
            </motion.div>

            {/* 2 & 3. Ownership Intelligence & Evidence List */}
            <div className="grid grid-cols-1 lg:grid-cols-12 gap-8">
              
              {/* LEFT COLUMN: INTELLIGENCE */}
              <div className="lg:col-span-4 space-y-6 flex flex-col">
                
                {/* OWNERSHIP INTELLIGENCE */}
                <motion.div variants={{ hidden: { opacity: 0, x: -20 }, show: { opacity: 1, x: 0, transition: { type: 'spring' } } }} className="bg-[#111827] border border-white/5 p-6 rounded-2xl shadow-[0_4px_20px_rgba(0,0,0,0.3)] relative overflow-hidden group hover:border-purple-500/30 hover:shadow-[0_10px_30px_rgba(168,85,247,0.1)] transition-all duration-300">
                  <div className="absolute top-0 right-0 p-4 opacity-5 pointer-events-none group-hover:scale-110 transition-transform duration-500">
                    <Building2 className="w-32 h-32 text-purple-500" />
                  </div>
                  <div className="flex items-center gap-3 mb-6">
                     <div className="p-2 bg-purple-500/10 text-purple-400 rounded-lg shadow-[0_0_10px_rgba(168,85,247,0.2)]">
                       <Building2 className="w-5 h-5" />
                     </div>
                     <h3 className="font-bold text-sm uppercase tracking-wide text-white relative z-10">Ownership Entity</h3>
                  </div>
                  
                  <div className="space-y-4 relative z-10">
                    <div>
                       <p className="text-[10px] font-mono text-slate-500 uppercase mb-1 drop-shadow">Likely Owner Data</p>
                       <p className="text-xl font-bold text-white leading-tight">{result.ownership_analysis.likely_owner}</p>
                    </div>
                    <div>
                       <p className="text-[10px] font-mono text-slate-500 uppercase mb-1 drop-shadow">Entity Type Classification</p>
                       <p className="text-sm font-medium text-slate-300">{result.ownership_analysis.owner_type}</p>
                    </div>
                  </div>
                </motion.div>

                {/* FLAGGED EVIDENCE LIST */}
                <motion.div variants={{ hidden: { opacity: 0, y: 20 }, show: { opacity: 1, y: 0, transition: { type: 'spring' } } }} className="bg-[#111827] border border-white/5 p-6 rounded-2xl shadow-[0_4px_20px_rgba(0,0,0,0.3)] flex flex-col hover:border-slate-500/30 transition-all duration-300 flex-1">
                  <h3 className="font-bold text-sm uppercase tracking-wide text-white mb-4">Evidentiary Discoveries</h3>
                  <div className="space-y-3 max-h-[400px] overflow-y-auto pr-2 custom-scrollbar focus:outline-none hover:[&::-webkit-scrollbar-thumb]:bg-slate-700">
                     {result.flagged_links.map((link, index) => (
                       <div key={index} className="p-3 bg-black/40 border border-white/5 rounded-xl hover:border-indigo-500/30 hover:bg-black/60 hover:-translate-y-0.5 hover:shadow-lg transition-all duration-200">
                         <div className="flex items-start justify-between mb-2 gap-2">
                           <span className="text-[10px] font-mono text-indigo-400 bg-indigo-500/10 px-2 py-0.5 rounded border border-indigo-500/20">{link.platform}</span>
                           <span className={`text-[9px] uppercase font-bold px-1.5 py-0.5 rounded border shadow-sm ${getRiskColor(link.risk)}`}>{link.risk}</span>
                         </div>
                         <p className="text-xs text-slate-300 font-mono break-all line-clamp-2 mb-2 group-hover:text-white transition-colors">{maskData(link.url, 'domain')}</p>
                       </div>
                     ))}
                  </div>
                </motion.div>
              </div>

              {/* RIGHT COLUMN: ACTION CENTER */}
              <motion.div variants={{ hidden: { opacity: 0, scale: 0.95 }, show: { opacity: 1, scale: 1, transition: { type: 'spring' } } }} className="lg:col-span-8 flex flex-col">
                <div className="bg-[#111827] border border-indigo-500/20 p-8 rounded-2xl shadow-[0_0_30px_rgba(79,70,229,0.1)] relative overflow-hidden flex-1 h-full flex flex-col group">
                  <div className="absolute inset-0 bg-gradient-to-br from-indigo-500/5 to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-500" />
                  <div className="absolute bottom-0 right-0 p-8 opacity-5 pointer-events-none group-hover:scale-105 transition-transform duration-700">
                    <Gavel className="w-64 h-64 text-indigo-500" />
                  </div>
                  
                  <div className="flex items-center gap-4 mb-8">
                     <div className="p-3 bg-indigo-500/20 text-indigo-400 rounded-xl border border-indigo-500/30 shadow-[0_0_15px_rgba(99,102,241,0.2)]">
                       <AlertOctagon className="w-6 h-6" />
                     </div>
                     <div>
                       <h3 className="font-bold text-xl uppercase tracking-wide text-indigo-300 drop-shadow">Case Summary & Protocol</h3>
                       <p className="text-xs font-mono text-slate-500">Legal Takedown Intelligence</p>
                     </div>
                  </div>

                  <div className="mb-8 p-6 bg-black/40 rounded-xl border border-white/5 relative z-10">
                     <p className="text-sm text-slate-300 italic leading-relaxed">
                       "{result.explanation}"
                     </p>
                  </div>
                  
                  <div className="space-y-4 relative z-10 flex-1">
                    <h4 className="text-[10px] font-mono text-slate-500 uppercase tracking-widest mb-4">Recommended Actions</h4>
                    {actionResult?.actions.map((action, idx) => (
                      <div key={idx} className="bg-[#0B0F1A] border border-white/10 hover:border-indigo-500/40 hover:shadow-[0_4px_20px_rgba(99,102,241,0.1)] hover:-translate-y-1 transition-all duration-300 p-6 rounded-xl flex items-center justify-between gap-6 group/action overflow-hidden relative">
                        <div className="absolute inset-0 bg-indigo-500/0 group-hover/action:bg-indigo-500/5 transition-colors duration-300" />
                        <div className="flex items-start gap-4 flex-1 relative z-10">
                          <div className="w-10 h-10 mt-1 rounded-xl bg-indigo-500/10 text-indigo-400 flex items-center justify-center font-black text-lg border border-indigo-500/20 shrink-0 shadow-[0_0_15px_rgba(99,102,241,0.15)] group-hover/action:bg-indigo-500 group-hover/action:text-white transition-all duration-300">
                            {idx + 1}
                          </div>
                          <div>
                            <div className="flex items-center gap-3 mb-1">
                              <h4 className="font-bold text-white text-base group-hover/action:text-indigo-200 transition-colors">{action.type}</h4>
                              <span className={`text-[10px] uppercase font-bold tracking-widest px-2 py-0.5 rounded-sm border ${getRiskColor(action.priority)}`}>
                                {action.priority}
                              </span>
                            </div>
                            <p className="text-sm text-slate-400 mt-1.5 max-w-2xl leading-relaxed">{action.description}</p>
                          </div>
                        </div>
                        <div className="shrink-0 flex items-center pl-4 border-l border-white/5 h-full">
                          <button className={`text-xs font-bold uppercase px-6 py-3 rounded-lg flex items-center gap-2 transition-all shadow-lg active:scale-95 ${
                            action.priority === 'Critical' || action.priority === 'High'
                              ? 'bg-red-500/10 text-red-400 hover:bg-red-500 hover:text-white border border-red-500/20 hover:border-red-500'
                              : 'bg-indigo-500/10 text-indigo-400 hover:bg-indigo-500 hover:text-white border border-indigo-500/20 hover:border-indigo-500'
                          }`}>
                            Execute <ChevronRight className="w-4 h-4" />
                          </button>
                        </div>
                      </div>
                    ))}
                  </div>
                </div>
              </motion.div>
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}
